// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/proto/client_message.proto

package ltd.finelink.tool.disk.protobuf;

public interface ClientMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.ClientMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.protobuf.ClientMessage.ClientMsgType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.protobuf.ClientMessage.ClientMsgType type = 1;</code>
   * @return The type.
   */
  ltd.finelink.tool.disk.protobuf.ClientMessage.ClientMsgType getType();

  /**
   * <code>string cid = 2;</code>
   * @return The cid.
   */
  java.lang.String getCid();
  /**
   * <code>string cid = 2;</code>
   * @return The bytes for cid.
   */
  com.google.protobuf.ByteString
      getCidBytes();

  /**
   * <code>string biz = 3;</code>
   * @return The biz.
   */
  java.lang.String getBiz();
  /**
   * <code>string biz = 3;</code>
   * @return The bytes for biz.
   */
  com.google.protobuf.ByteString
      getBizBytes();

  /**
   * <code>optional string traceId = 4;</code>
   * @return Whether the traceId field is set.
   */
  boolean hasTraceId();
  /**
   * <code>optional string traceId = 4;</code>
   * @return The traceId.
   */
  java.lang.String getTraceId();
  /**
   * <code>optional string traceId = 4;</code>
   * @return The bytes for traceId.
   */
  com.google.protobuf.ByteString
      getTraceIdBytes();

  /**
   * <code>int64 timestamp = 5;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>repeated .protobuf.ClientBody body = 6;</code>
   */
  java.util.List<ltd.finelink.tool.disk.protobuf.ClientBody> 
      getBodyList();
  /**
   * <code>repeated .protobuf.ClientBody body = 6;</code>
   */
  ltd.finelink.tool.disk.protobuf.ClientBody getBody(int index);
  /**
   * <code>repeated .protobuf.ClientBody body = 6;</code>
   */
  int getBodyCount();
  /**
   * <code>repeated .protobuf.ClientBody body = 6;</code>
   */
  java.util.List<? extends ltd.finelink.tool.disk.protobuf.ClientBodyOrBuilder> 
      getBodyOrBuilderList();
  /**
   * <code>repeated .protobuf.ClientBody body = 6;</code>
   */
  ltd.finelink.tool.disk.protobuf.ClientBodyOrBuilder getBodyOrBuilder(
      int index);
}
