// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/proto/client_message.proto

package ltd.finelink.tool.disk.protobuf;

public final class ClientProto {
  private ClientProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_ClientBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_ClientBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_ClientMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_ClientMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$resources/proto/client_message.proto\022\010" +
      "protobuf\"\256\001\n\nClientBody\022\014\n\004type\030\001 \001(\005\022\020\n" +
      "\003sub\030\002 \001(\tH\000\210\001\001\022\021\n\004toId\030\003 \001(\tH\001\210\001\001\022\020\n\003si" +
      "d\030\004 \001(\tH\002\210\001\001\022\024\n\007msgType\030\005 \001(\tH\003\210\001\001\022\024\n\007co" +
      "ntent\030\006 \001(\014H\004\210\001\001B\006\n\004_subB\007\n\005_toIdB\006\n\004_si" +
      "dB\n\n\010_msgTypeB\n\n\010_content\"\225\002\n\rClientMess" +
      "age\0223\n\004type\030\001 \001(\0162%.protobuf.ClientMessa" +
      "ge.ClientMsgType\022\013\n\003cid\030\002 \001(\t\022\013\n\003biz\030\003 \001" +
      "(\t\022\024\n\007traceId\030\004 \001(\tH\000\210\001\001\022\021\n\ttimestamp\030\005 " +
      "\001(\003\022\"\n\004body\030\006 \003(\0132\024.protobuf.ClientBody\"" +
      "\\\n\rClientMsgType\022\010\n\004CHAT\020\000\022\013\n\007CONFIRM\020\001\022" +
      "\r\n\tHEARTBEAT\020\002\022\n\n\006CUSTOM\020\003\022\r\n\tSUBSCRIBE\020" +
      "\004\022\n\n\006WEBRTC\020\005B\n\n\010_traceIdB0\n\037ltd.finelin" +
      "k.tool.disk.protobufB\013ClientProtoP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protobuf_ClientBody_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_ClientBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_ClientBody_descriptor,
        new java.lang.String[] { "Type", "Sub", "ToId", "Sid", "MsgType", "Content", "Sub", "ToId", "Sid", "MsgType", "Content", });
    internal_static_protobuf_ClientMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_ClientMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_ClientMessage_descriptor,
        new java.lang.String[] { "Type", "Cid", "Biz", "TraceId", "Timestamp", "Body", "TraceId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
