// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/proto/server_message.proto

package ltd.finelink.tool.disk.protobuf;

public interface ServerBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.ServerBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 type = 1;</code>
   * @return The type.
   */
  int getType();

  /**
   * <code>string sid = 2;</code>
   * @return The sid.
   */
  java.lang.String getSid();
  /**
   * <code>string sid = 2;</code>
   * @return The bytes for sid.
   */
  com.google.protobuf.ByteString
      getSidBytes();

  /**
   * <code>optional string code = 3;</code>
   * @return Whether the code field is set.
   */
  boolean hasCode();
  /**
   * <code>optional string code = 3;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>optional string code = 3;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>optional string msgType = 4;</code>
   * @return Whether the msgType field is set.
   */
  boolean hasMsgType();
  /**
   * <code>optional string msgType = 4;</code>
   * @return The msgType.
   */
  java.lang.String getMsgType();
  /**
   * <code>optional string msgType = 4;</code>
   * @return The bytes for msgType.
   */
  com.google.protobuf.ByteString
      getMsgTypeBytes();

  /**
   * <code>optional string msg = 5;</code>
   * @return Whether the msg field is set.
   */
  boolean hasMsg();
  /**
   * <code>optional string msg = 5;</code>
   * @return The msg.
   */
  java.lang.String getMsg();
  /**
   * <code>optional string msg = 5;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>optional string cid = 6;</code>
   * @return Whether the cid field is set.
   */
  boolean hasCid();
  /**
   * <code>optional string cid = 6;</code>
   * @return The cid.
   */
  java.lang.String getCid();
  /**
   * <code>optional string cid = 6;</code>
   * @return The bytes for cid.
   */
  com.google.protobuf.ByteString
      getCidBytes();

  /**
   * <code>optional string sub = 7;</code>
   * @return Whether the sub field is set.
   */
  boolean hasSub();
  /**
   * <code>optional string sub = 7;</code>
   * @return The sub.
   */
  java.lang.String getSub();
  /**
   * <code>optional string sub = 7;</code>
   * @return The bytes for sub.
   */
  com.google.protobuf.ByteString
      getSubBytes();

  /**
   * <code>optional string fromId = 8;</code>
   * @return Whether the fromId field is set.
   */
  boolean hasFromId();
  /**
   * <code>optional string fromId = 8;</code>
   * @return The fromId.
   */
  java.lang.String getFromId();
  /**
   * <code>optional string fromId = 8;</code>
   * @return The bytes for fromId.
   */
  com.google.protobuf.ByteString
      getFromIdBytes();

  /**
   * <code>optional string toId = 9;</code>
   * @return Whether the toId field is set.
   */
  boolean hasToId();
  /**
   * <code>optional string toId = 9;</code>
   * @return The toId.
   */
  java.lang.String getToId();
  /**
   * <code>optional string toId = 9;</code>
   * @return The bytes for toId.
   */
  com.google.protobuf.ByteString
      getToIdBytes();

  /**
   * <code>optional string gid = 10;</code>
   * @return Whether the gid field is set.
   */
  boolean hasGid();
  /**
   * <code>optional string gid = 10;</code>
   * @return The gid.
   */
  java.lang.String getGid();
  /**
   * <code>optional string gid = 10;</code>
   * @return The bytes for gid.
   */
  com.google.protobuf.ByteString
      getGidBytes();

  /**
   * <code>optional int64 timestamp = 11;</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <code>optional int64 timestamp = 11;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>optional bytes content = 12;</code>
   * @return Whether the content field is set.
   */
  boolean hasContent();
  /**
   * <code>optional bytes content = 12;</code>
   * @return The content.
   */
  com.google.protobuf.ByteString getContent();
}
