// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/proto/server_message.proto

package ltd.finelink.tool.disk.protobuf;

/**
 * Protobuf type {@code protobuf.ServerBody}
 */
public final class ServerBody extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protobuf.ServerBody)
    ServerBodyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ServerBody.newBuilder() to construct.
  private ServerBody(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ServerBody() {
    sid_ = "";
    code_ = "";
    msgType_ = "";
    msg_ = "";
    cid_ = "";
    sub_ = "";
    fromId_ = "";
    toId_ = "";
    gid_ = "";
    content_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ServerBody();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ServerBody(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            type_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            sid_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            code_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000002;
            msgType_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000004;
            msg_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000008;
            cid_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000010;
            sub_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000020;
            fromId_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000040;
            toId_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000080;
            gid_ = s;
            break;
          }
          case 88: {
            bitField0_ |= 0x00000100;
            timestamp_ = input.readInt64();
            break;
          }
          case 98: {
            bitField0_ |= 0x00000200;
            content_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ltd.finelink.tool.disk.protobuf.ServerProto.internal_static_protobuf_ServerBody_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ltd.finelink.tool.disk.protobuf.ServerProto.internal_static_protobuf_ServerBody_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ltd.finelink.tool.disk.protobuf.ServerBody.class, ltd.finelink.tool.disk.protobuf.ServerBody.Builder.class);
  }

  private int bitField0_;
  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <code>int32 type = 1;</code>
   * @return The type.
   */
  @java.lang.Override
  public int getType() {
    return type_;
  }

  public static final int SID_FIELD_NUMBER = 2;
  private volatile java.lang.Object sid_;
  /**
   * <code>string sid = 2;</code>
   * @return The sid.
   */
  @java.lang.Override
  public java.lang.String getSid() {
    java.lang.Object ref = sid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sid_ = s;
      return s;
    }
  }
  /**
   * <code>string sid = 2;</code>
   * @return The bytes for sid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSidBytes() {
    java.lang.Object ref = sid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CODE_FIELD_NUMBER = 3;
  private volatile java.lang.Object code_;
  /**
   * <code>optional string code = 3;</code>
   * @return Whether the code field is set.
   */
  @java.lang.Override
  public boolean hasCode() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string code = 3;</code>
   * @return The code.
   */
  @java.lang.Override
  public java.lang.String getCode() {
    java.lang.Object ref = code_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      code_ = s;
      return s;
    }
  }
  /**
   * <code>optional string code = 3;</code>
   * @return The bytes for code.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCodeBytes() {
    java.lang.Object ref = code_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      code_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MSGTYPE_FIELD_NUMBER = 4;
  private volatile java.lang.Object msgType_;
  /**
   * <code>optional string msgType = 4;</code>
   * @return Whether the msgType field is set.
   */
  @java.lang.Override
  public boolean hasMsgType() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string msgType = 4;</code>
   * @return The msgType.
   */
  @java.lang.Override
  public java.lang.String getMsgType() {
    java.lang.Object ref = msgType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      msgType_ = s;
      return s;
    }
  }
  /**
   * <code>optional string msgType = 4;</code>
   * @return The bytes for msgType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMsgTypeBytes() {
    java.lang.Object ref = msgType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msgType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MSG_FIELD_NUMBER = 5;
  private volatile java.lang.Object msg_;
  /**
   * <code>optional string msg = 5;</code>
   * @return Whether the msg field is set.
   */
  @java.lang.Override
  public boolean hasMsg() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string msg = 5;</code>
   * @return The msg.
   */
  @java.lang.Override
  public java.lang.String getMsg() {
    java.lang.Object ref = msg_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      msg_ = s;
      return s;
    }
  }
  /**
   * <code>optional string msg = 5;</code>
   * @return The bytes for msg.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMsgBytes() {
    java.lang.Object ref = msg_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CID_FIELD_NUMBER = 6;
  private volatile java.lang.Object cid_;
  /**
   * <code>optional string cid = 6;</code>
   * @return Whether the cid field is set.
   */
  @java.lang.Override
  public boolean hasCid() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional string cid = 6;</code>
   * @return The cid.
   */
  @java.lang.Override
  public java.lang.String getCid() {
    java.lang.Object ref = cid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cid_ = s;
      return s;
    }
  }
  /**
   * <code>optional string cid = 6;</code>
   * @return The bytes for cid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCidBytes() {
    java.lang.Object ref = cid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUB_FIELD_NUMBER = 7;
  private volatile java.lang.Object sub_;
  /**
   * <code>optional string sub = 7;</code>
   * @return Whether the sub field is set.
   */
  @java.lang.Override
  public boolean hasSub() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional string sub = 7;</code>
   * @return The sub.
   */
  @java.lang.Override
  public java.lang.String getSub() {
    java.lang.Object ref = sub_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sub_ = s;
      return s;
    }
  }
  /**
   * <code>optional string sub = 7;</code>
   * @return The bytes for sub.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSubBytes() {
    java.lang.Object ref = sub_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sub_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FROMID_FIELD_NUMBER = 8;
  private volatile java.lang.Object fromId_;
  /**
   * <code>optional string fromId = 8;</code>
   * @return Whether the fromId field is set.
   */
  @java.lang.Override
  public boolean hasFromId() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional string fromId = 8;</code>
   * @return The fromId.
   */
  @java.lang.Override
  public java.lang.String getFromId() {
    java.lang.Object ref = fromId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fromId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string fromId = 8;</code>
   * @return The bytes for fromId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFromIdBytes() {
    java.lang.Object ref = fromId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fromId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOID_FIELD_NUMBER = 9;
  private volatile java.lang.Object toId_;
  /**
   * <code>optional string toId = 9;</code>
   * @return Whether the toId field is set.
   */
  @java.lang.Override
  public boolean hasToId() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional string toId = 9;</code>
   * @return The toId.
   */
  @java.lang.Override
  public java.lang.String getToId() {
    java.lang.Object ref = toId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      toId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string toId = 9;</code>
   * @return The bytes for toId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getToIdBytes() {
    java.lang.Object ref = toId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      toId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GID_FIELD_NUMBER = 10;
  private volatile java.lang.Object gid_;
  /**
   * <code>optional string gid = 10;</code>
   * @return Whether the gid field is set.
   */
  @java.lang.Override
  public boolean hasGid() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <code>optional string gid = 10;</code>
   * @return The gid.
   */
  @java.lang.Override
  public java.lang.String getGid() {
    java.lang.Object ref = gid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      gid_ = s;
      return s;
    }
  }
  /**
   * <code>optional string gid = 10;</code>
   * @return The bytes for gid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGidBytes() {
    java.lang.Object ref = gid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 11;
  private long timestamp_;
  /**
   * <code>optional int64 timestamp = 11;</code>
   * @return Whether the timestamp field is set.
   */
  @java.lang.Override
  public boolean hasTimestamp() {
    return ((bitField0_ & 0x00000100) != 0);
  }
  /**
   * <code>optional int64 timestamp = 11;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int CONTENT_FIELD_NUMBER = 12;
  private com.google.protobuf.ByteString content_;
  /**
   * <code>optional bytes content = 12;</code>
   * @return Whether the content field is set.
   */
  @java.lang.Override
  public boolean hasContent() {
    return ((bitField0_ & 0x00000200) != 0);
  }
  /**
   * <code>optional bytes content = 12;</code>
   * @return The content.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getContent() {
    return content_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != 0) {
      output.writeInt32(1, type_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sid_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sid_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, code_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, msgType_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, msg_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, cid_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, sub_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, fromId_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, toId_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, gid_);
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      output.writeInt64(11, timestamp_);
    }
    if (((bitField0_ & 0x00000200) != 0)) {
      output.writeBytes(12, content_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, type_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sid_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sid_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, code_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, msgType_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, msg_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, cid_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, sub_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, fromId_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, toId_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, gid_);
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(11, timestamp_);
    }
    if (((bitField0_ & 0x00000200) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(12, content_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ltd.finelink.tool.disk.protobuf.ServerBody)) {
      return super.equals(obj);
    }
    ltd.finelink.tool.disk.protobuf.ServerBody other = (ltd.finelink.tool.disk.protobuf.ServerBody) obj;

    if (getType()
        != other.getType()) return false;
    if (!getSid()
        .equals(other.getSid())) return false;
    if (hasCode() != other.hasCode()) return false;
    if (hasCode()) {
      if (!getCode()
          .equals(other.getCode())) return false;
    }
    if (hasMsgType() != other.hasMsgType()) return false;
    if (hasMsgType()) {
      if (!getMsgType()
          .equals(other.getMsgType())) return false;
    }
    if (hasMsg() != other.hasMsg()) return false;
    if (hasMsg()) {
      if (!getMsg()
          .equals(other.getMsg())) return false;
    }
    if (hasCid() != other.hasCid()) return false;
    if (hasCid()) {
      if (!getCid()
          .equals(other.getCid())) return false;
    }
    if (hasSub() != other.hasSub()) return false;
    if (hasSub()) {
      if (!getSub()
          .equals(other.getSub())) return false;
    }
    if (hasFromId() != other.hasFromId()) return false;
    if (hasFromId()) {
      if (!getFromId()
          .equals(other.getFromId())) return false;
    }
    if (hasToId() != other.hasToId()) return false;
    if (hasToId()) {
      if (!getToId()
          .equals(other.getToId())) return false;
    }
    if (hasGid() != other.hasGid()) return false;
    if (hasGid()) {
      if (!getGid()
          .equals(other.getGid())) return false;
    }
    if (hasTimestamp() != other.hasTimestamp()) return false;
    if (hasTimestamp()) {
      if (getTimestamp()
          != other.getTimestamp()) return false;
    }
    if (hasContent() != other.hasContent()) return false;
    if (hasContent()) {
      if (!getContent()
          .equals(other.getContent())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType();
    hash = (37 * hash) + SID_FIELD_NUMBER;
    hash = (53 * hash) + getSid().hashCode();
    if (hasCode()) {
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode().hashCode();
    }
    if (hasMsgType()) {
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMsgType().hashCode();
    }
    if (hasMsg()) {
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
    }
    if (hasCid()) {
      hash = (37 * hash) + CID_FIELD_NUMBER;
      hash = (53 * hash) + getCid().hashCode();
    }
    if (hasSub()) {
      hash = (37 * hash) + SUB_FIELD_NUMBER;
      hash = (53 * hash) + getSub().hashCode();
    }
    if (hasFromId()) {
      hash = (37 * hash) + FROMID_FIELD_NUMBER;
      hash = (53 * hash) + getFromId().hashCode();
    }
    if (hasToId()) {
      hash = (37 * hash) + TOID_FIELD_NUMBER;
      hash = (53 * hash) + getToId().hashCode();
    }
    if (hasGid()) {
      hash = (37 * hash) + GID_FIELD_NUMBER;
      hash = (53 * hash) + getGid().hashCode();
    }
    if (hasTimestamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
    }
    if (hasContent()) {
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ltd.finelink.tool.disk.protobuf.ServerBody parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ltd.finelink.tool.disk.protobuf.ServerBody parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ltd.finelink.tool.disk.protobuf.ServerBody parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ltd.finelink.tool.disk.protobuf.ServerBody parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ltd.finelink.tool.disk.protobuf.ServerBody parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ltd.finelink.tool.disk.protobuf.ServerBody parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ltd.finelink.tool.disk.protobuf.ServerBody parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ltd.finelink.tool.disk.protobuf.ServerBody parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ltd.finelink.tool.disk.protobuf.ServerBody parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ltd.finelink.tool.disk.protobuf.ServerBody parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ltd.finelink.tool.disk.protobuf.ServerBody parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ltd.finelink.tool.disk.protobuf.ServerBody parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ltd.finelink.tool.disk.protobuf.ServerBody prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protobuf.ServerBody}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protobuf.ServerBody)
      ltd.finelink.tool.disk.protobuf.ServerBodyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ltd.finelink.tool.disk.protobuf.ServerProto.internal_static_protobuf_ServerBody_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ltd.finelink.tool.disk.protobuf.ServerProto.internal_static_protobuf_ServerBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ltd.finelink.tool.disk.protobuf.ServerBody.class, ltd.finelink.tool.disk.protobuf.ServerBody.Builder.class);
    }

    // Construct using ltd.finelink.tool.disk.protobuf.ServerBody.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      type_ = 0;

      sid_ = "";

      code_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      msgType_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      msg_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      cid_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      sub_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      fromId_ = "";
      bitField0_ = (bitField0_ & ~0x00000020);
      toId_ = "";
      bitField0_ = (bitField0_ & ~0x00000040);
      gid_ = "";
      bitField0_ = (bitField0_ & ~0x00000080);
      timestamp_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000100);
      content_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000200);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ltd.finelink.tool.disk.protobuf.ServerProto.internal_static_protobuf_ServerBody_descriptor;
    }

    @java.lang.Override
    public ltd.finelink.tool.disk.protobuf.ServerBody getDefaultInstanceForType() {
      return ltd.finelink.tool.disk.protobuf.ServerBody.getDefaultInstance();
    }

    @java.lang.Override
    public ltd.finelink.tool.disk.protobuf.ServerBody build() {
      ltd.finelink.tool.disk.protobuf.ServerBody result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ltd.finelink.tool.disk.protobuf.ServerBody buildPartial() {
      ltd.finelink.tool.disk.protobuf.ServerBody result = new ltd.finelink.tool.disk.protobuf.ServerBody(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.type_ = type_;
      result.sid_ = sid_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.code_ = code_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.msgType_ = msgType_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.msg_ = msg_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        to_bitField0_ |= 0x00000008;
      }
      result.cid_ = cid_;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        to_bitField0_ |= 0x00000010;
      }
      result.sub_ = sub_;
      if (((from_bitField0_ & 0x00000020) != 0)) {
        to_bitField0_ |= 0x00000020;
      }
      result.fromId_ = fromId_;
      if (((from_bitField0_ & 0x00000040) != 0)) {
        to_bitField0_ |= 0x00000040;
      }
      result.toId_ = toId_;
      if (((from_bitField0_ & 0x00000080) != 0)) {
        to_bitField0_ |= 0x00000080;
      }
      result.gid_ = gid_;
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.timestamp_ = timestamp_;
        to_bitField0_ |= 0x00000100;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        to_bitField0_ |= 0x00000200;
      }
      result.content_ = content_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ltd.finelink.tool.disk.protobuf.ServerBody) {
        return mergeFrom((ltd.finelink.tool.disk.protobuf.ServerBody)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ltd.finelink.tool.disk.protobuf.ServerBody other) {
      if (other == ltd.finelink.tool.disk.protobuf.ServerBody.getDefaultInstance()) return this;
      if (other.getType() != 0) {
        setType(other.getType());
      }
      if (!other.getSid().isEmpty()) {
        sid_ = other.sid_;
        onChanged();
      }
      if (other.hasCode()) {
        bitField0_ |= 0x00000001;
        code_ = other.code_;
        onChanged();
      }
      if (other.hasMsgType()) {
        bitField0_ |= 0x00000002;
        msgType_ = other.msgType_;
        onChanged();
      }
      if (other.hasMsg()) {
        bitField0_ |= 0x00000004;
        msg_ = other.msg_;
        onChanged();
      }
      if (other.hasCid()) {
        bitField0_ |= 0x00000008;
        cid_ = other.cid_;
        onChanged();
      }
      if (other.hasSub()) {
        bitField0_ |= 0x00000010;
        sub_ = other.sub_;
        onChanged();
      }
      if (other.hasFromId()) {
        bitField0_ |= 0x00000020;
        fromId_ = other.fromId_;
        onChanged();
      }
      if (other.hasToId()) {
        bitField0_ |= 0x00000040;
        toId_ = other.toId_;
        onChanged();
      }
      if (other.hasGid()) {
        bitField0_ |= 0x00000080;
        gid_ = other.gid_;
        onChanged();
      }
      if (other.hasTimestamp()) {
        setTimestamp(other.getTimestamp());
      }
      if (other.hasContent()) {
        setContent(other.getContent());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ltd.finelink.tool.disk.protobuf.ServerBody parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ltd.finelink.tool.disk.protobuf.ServerBody) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int type_ ;
    /**
     * <code>int32 type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }
    /**
     * <code>int32 type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(int value) {
      
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object sid_ = "";
    /**
     * <code>string sid = 2;</code>
     * @return The sid.
     */
    public java.lang.String getSid() {
      java.lang.Object ref = sid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sid = 2;</code>
     * @return The bytes for sid.
     */
    public com.google.protobuf.ByteString
        getSidBytes() {
      java.lang.Object ref = sid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sid = 2;</code>
     * @param value The sid to set.
     * @return This builder for chaining.
     */
    public Builder setSid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sid = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSid() {
      
      sid_ = getDefaultInstance().getSid();
      onChanged();
      return this;
    }
    /**
     * <code>string sid = 2;</code>
     * @param value The bytes for sid to set.
     * @return This builder for chaining.
     */
    public Builder setSidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object code_ = "";
    /**
     * <code>optional string code = 3;</code>
     * @return Whether the code field is set.
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string code = 3;</code>
     * @return The code.
     */
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        code_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string code = 3;</code>
     * @return The bytes for code.
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string code = 3;</code>
     * @param value The code to set.
     * @return This builder for chaining.
     */
    public Builder setCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      code_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string code = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCode() {
      bitField0_ = (bitField0_ & ~0x00000001);
      code_ = getDefaultInstance().getCode();
      onChanged();
      return this;
    }
    /**
     * <code>optional string code = 3;</code>
     * @param value The bytes for code to set.
     * @return This builder for chaining.
     */
    public Builder setCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      code_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object msgType_ = "";
    /**
     * <code>optional string msgType = 4;</code>
     * @return Whether the msgType field is set.
     */
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string msgType = 4;</code>
     * @return The msgType.
     */
    public java.lang.String getMsgType() {
      java.lang.Object ref = msgType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string msgType = 4;</code>
     * @return The bytes for msgType.
     */
    public com.google.protobuf.ByteString
        getMsgTypeBytes() {
      java.lang.Object ref = msgType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string msgType = 4;</code>
     * @param value The msgType to set.
     * @return This builder for chaining.
     */
    public Builder setMsgType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      msgType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string msgType = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      msgType_ = getDefaultInstance().getMsgType();
      onChanged();
      return this;
    }
    /**
     * <code>optional string msgType = 4;</code>
     * @param value The bytes for msgType to set.
     * @return This builder for chaining.
     */
    public Builder setMsgTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000002;
      msgType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object msg_ = "";
    /**
     * <code>optional string msg = 5;</code>
     * @return Whether the msg field is set.
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string msg = 5;</code>
     * @return The msg.
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string msg = 5;</code>
     * @return The bytes for msg.
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string msg = 5;</code>
     * @param value The msg to set.
     * @return This builder for chaining.
     */
    public Builder setMsg(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      msg_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string msg = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsg() {
      bitField0_ = (bitField0_ & ~0x00000004);
      msg_ = getDefaultInstance().getMsg();
      onChanged();
      return this;
    }
    /**
     * <code>optional string msg = 5;</code>
     * @param value The bytes for msg to set.
     * @return This builder for chaining.
     */
    public Builder setMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000004;
      msg_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cid_ = "";
    /**
     * <code>optional string cid = 6;</code>
     * @return Whether the cid field is set.
     */
    public boolean hasCid() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string cid = 6;</code>
     * @return The cid.
     */
    public java.lang.String getCid() {
      java.lang.Object ref = cid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string cid = 6;</code>
     * @return The bytes for cid.
     */
    public com.google.protobuf.ByteString
        getCidBytes() {
      java.lang.Object ref = cid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string cid = 6;</code>
     * @param value The cid to set.
     * @return This builder for chaining.
     */
    public Builder setCid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      cid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string cid = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCid() {
      bitField0_ = (bitField0_ & ~0x00000008);
      cid_ = getDefaultInstance().getCid();
      onChanged();
      return this;
    }
    /**
     * <code>optional string cid = 6;</code>
     * @param value The bytes for cid to set.
     * @return This builder for chaining.
     */
    public Builder setCidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000008;
      cid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sub_ = "";
    /**
     * <code>optional string sub = 7;</code>
     * @return Whether the sub field is set.
     */
    public boolean hasSub() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string sub = 7;</code>
     * @return The sub.
     */
    public java.lang.String getSub() {
      java.lang.Object ref = sub_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sub_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string sub = 7;</code>
     * @return The bytes for sub.
     */
    public com.google.protobuf.ByteString
        getSubBytes() {
      java.lang.Object ref = sub_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sub_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string sub = 7;</code>
     * @param value The sub to set.
     * @return This builder for chaining.
     */
    public Builder setSub(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      sub_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string sub = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSub() {
      bitField0_ = (bitField0_ & ~0x00000010);
      sub_ = getDefaultInstance().getSub();
      onChanged();
      return this;
    }
    /**
     * <code>optional string sub = 7;</code>
     * @param value The bytes for sub to set.
     * @return This builder for chaining.
     */
    public Builder setSubBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000010;
      sub_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object fromId_ = "";
    /**
     * <code>optional string fromId = 8;</code>
     * @return Whether the fromId field is set.
     */
    public boolean hasFromId() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string fromId = 8;</code>
     * @return The fromId.
     */
    public java.lang.String getFromId() {
      java.lang.Object ref = fromId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string fromId = 8;</code>
     * @return The bytes for fromId.
     */
    public com.google.protobuf.ByteString
        getFromIdBytes() {
      java.lang.Object ref = fromId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string fromId = 8;</code>
     * @param value The fromId to set.
     * @return This builder for chaining.
     */
    public Builder setFromId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      fromId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string fromId = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearFromId() {
      bitField0_ = (bitField0_ & ~0x00000020);
      fromId_ = getDefaultInstance().getFromId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string fromId = 8;</code>
     * @param value The bytes for fromId to set.
     * @return This builder for chaining.
     */
    public Builder setFromIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000020;
      fromId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object toId_ = "";
    /**
     * <code>optional string toId = 9;</code>
     * @return Whether the toId field is set.
     */
    public boolean hasToId() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional string toId = 9;</code>
     * @return The toId.
     */
    public java.lang.String getToId() {
      java.lang.Object ref = toId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string toId = 9;</code>
     * @return The bytes for toId.
     */
    public com.google.protobuf.ByteString
        getToIdBytes() {
      java.lang.Object ref = toId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string toId = 9;</code>
     * @param value The toId to set.
     * @return This builder for chaining.
     */
    public Builder setToId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      toId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string toId = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearToId() {
      bitField0_ = (bitField0_ & ~0x00000040);
      toId_ = getDefaultInstance().getToId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string toId = 9;</code>
     * @param value The bytes for toId to set.
     * @return This builder for chaining.
     */
    public Builder setToIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000040;
      toId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object gid_ = "";
    /**
     * <code>optional string gid = 10;</code>
     * @return Whether the gid field is set.
     */
    public boolean hasGid() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional string gid = 10;</code>
     * @return The gid.
     */
    public java.lang.String getGid() {
      java.lang.Object ref = gid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string gid = 10;</code>
     * @return The bytes for gid.
     */
    public com.google.protobuf.ByteString
        getGidBytes() {
      java.lang.Object ref = gid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string gid = 10;</code>
     * @param value The gid to set.
     * @return This builder for chaining.
     */
    public Builder setGid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
      gid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string gid = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearGid() {
      bitField0_ = (bitField0_ & ~0x00000080);
      gid_ = getDefaultInstance().getGid();
      onChanged();
      return this;
    }
    /**
     * <code>optional string gid = 10;</code>
     * @param value The bytes for gid to set.
     * @return This builder for chaining.
     */
    public Builder setGidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000080;
      gid_ = value;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>optional int64 timestamp = 11;</code>
     * @return Whether the timestamp field is set.
     */
    @java.lang.Override
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional int64 timestamp = 11;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>optional int64 timestamp = 11;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {
      bitField0_ |= 0x00000100;
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 timestamp = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000100);
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes content = 12;</code>
     * @return Whether the content field is set.
     */
    @java.lang.Override
    public boolean hasContent() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>optional bytes content = 12;</code>
     * @return The content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }
    /**
     * <code>optional bytes content = 12;</code>
     * @param value The content to set.
     * @return This builder for chaining.
     */
    public Builder setContent(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
      content_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes content = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearContent() {
      bitField0_ = (bitField0_ & ~0x00000200);
      content_ = getDefaultInstance().getContent();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protobuf.ServerBody)
  }

  // @@protoc_insertion_point(class_scope:protobuf.ServerBody)
  private static final ltd.finelink.tool.disk.protobuf.ServerBody DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ltd.finelink.tool.disk.protobuf.ServerBody();
  }

  public static ltd.finelink.tool.disk.protobuf.ServerBody getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ServerBody>
      PARSER = new com.google.protobuf.AbstractParser<ServerBody>() {
    @java.lang.Override
    public ServerBody parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ServerBody(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ServerBody> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ServerBody> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ltd.finelink.tool.disk.protobuf.ServerBody getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

