// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/proto/server_message.proto

package ltd.finelink.tool.disk.protobuf;

/**
 * Protobuf type {@code protobuf.ServerMessage}
 */
public final class ServerMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protobuf.ServerMessage)
    ServerMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ServerMessage.newBuilder() to construct.
  private ServerMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ServerMessage() {
    type_ = 0;
    biz_ = "";
    traceId_ = "";
    body_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ServerMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ServerMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            biz_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            traceId_ = s;
            break;
          }
          case 32: {

            timestamp_ = input.readInt64();
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              body_ = new java.util.ArrayList<ltd.finelink.tool.disk.protobuf.ServerBody>();
              mutable_bitField0_ |= 0x00000002;
            }
            body_.add(
                input.readMessage(ltd.finelink.tool.disk.protobuf.ServerBody.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        body_ = java.util.Collections.unmodifiableList(body_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ltd.finelink.tool.disk.protobuf.ServerProto.internal_static_protobuf_ServerMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ltd.finelink.tool.disk.protobuf.ServerProto.internal_static_protobuf_ServerMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ltd.finelink.tool.disk.protobuf.ServerMessage.class, ltd.finelink.tool.disk.protobuf.ServerMessage.Builder.class);
  }

  /**
   * Protobuf enum {@code protobuf.ServerMessage.ServerMsgType}
   */
  public enum ServerMsgType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SYSTEM = 0;</code>
     */
    SYSTEM(0),
    /**
     * <code>CHAT = 1;</code>
     */
    CHAT(1),
    /**
     * <code>CUSTOM = 2;</code>
     */
    CUSTOM(2),
    /**
     * <code>SUBSCRIBE = 3;</code>
     */
    SUBSCRIBE(3),
    /**
     * <code>WEBRTC = 4;</code>
     */
    WEBRTC(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SYSTEM = 0;</code>
     */
    public static final int SYSTEM_VALUE = 0;
    /**
     * <code>CHAT = 1;</code>
     */
    public static final int CHAT_VALUE = 1;
    /**
     * <code>CUSTOM = 2;</code>
     */
    public static final int CUSTOM_VALUE = 2;
    /**
     * <code>SUBSCRIBE = 3;</code>
     */
    public static final int SUBSCRIBE_VALUE = 3;
    /**
     * <code>WEBRTC = 4;</code>
     */
    public static final int WEBRTC_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ServerMsgType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ServerMsgType forNumber(int value) {
      switch (value) {
        case 0: return SYSTEM;
        case 1: return CHAT;
        case 2: return CUSTOM;
        case 3: return SUBSCRIBE;
        case 4: return WEBRTC;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ServerMsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ServerMsgType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ServerMsgType>() {
            public ServerMsgType findValueByNumber(int number) {
              return ServerMsgType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ltd.finelink.tool.disk.protobuf.ServerMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final ServerMsgType[] VALUES = values();

    public static ServerMsgType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ServerMsgType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protobuf.ServerMessage.ServerMsgType)
  }

  private int bitField0_;
  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <code>.protobuf.ServerMessage.ServerMsgType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.protobuf.ServerMessage.ServerMsgType type = 1;</code>
   * @return The type.
   */
  @java.lang.Override public ltd.finelink.tool.disk.protobuf.ServerMessage.ServerMsgType getType() {
    @SuppressWarnings("deprecation")
    ltd.finelink.tool.disk.protobuf.ServerMessage.ServerMsgType result = ltd.finelink.tool.disk.protobuf.ServerMessage.ServerMsgType.valueOf(type_);
    return result == null ? ltd.finelink.tool.disk.protobuf.ServerMessage.ServerMsgType.UNRECOGNIZED : result;
  }

  public static final int BIZ_FIELD_NUMBER = 2;
  private volatile java.lang.Object biz_;
  /**
   * <code>string biz = 2;</code>
   * @return The biz.
   */
  @java.lang.Override
  public java.lang.String getBiz() {
    java.lang.Object ref = biz_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      biz_ = s;
      return s;
    }
  }
  /**
   * <code>string biz = 2;</code>
   * @return The bytes for biz.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBizBytes() {
    java.lang.Object ref = biz_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      biz_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRACEID_FIELD_NUMBER = 3;
  private volatile java.lang.Object traceId_;
  /**
   * <code>optional string traceId = 3;</code>
   * @return Whether the traceId field is set.
   */
  @java.lang.Override
  public boolean hasTraceId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string traceId = 3;</code>
   * @return The traceId.
   */
  @java.lang.Override
  public java.lang.String getTraceId() {
    java.lang.Object ref = traceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      traceId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string traceId = 3;</code>
   * @return The bytes for traceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTraceIdBytes() {
    java.lang.Object ref = traceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      traceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 4;
  private long timestamp_;
  /**
   * <code>int64 timestamp = 4;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int BODY_FIELD_NUMBER = 5;
  private java.util.List<ltd.finelink.tool.disk.protobuf.ServerBody> body_;
  /**
   * <code>repeated .protobuf.ServerBody body = 5;</code>
   */
  @java.lang.Override
  public java.util.List<ltd.finelink.tool.disk.protobuf.ServerBody> getBodyList() {
    return body_;
  }
  /**
   * <code>repeated .protobuf.ServerBody body = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends ltd.finelink.tool.disk.protobuf.ServerBodyOrBuilder> 
      getBodyOrBuilderList() {
    return body_;
  }
  /**
   * <code>repeated .protobuf.ServerBody body = 5;</code>
   */
  @java.lang.Override
  public int getBodyCount() {
    return body_.size();
  }
  /**
   * <code>repeated .protobuf.ServerBody body = 5;</code>
   */
  @java.lang.Override
  public ltd.finelink.tool.disk.protobuf.ServerBody getBody(int index) {
    return body_.get(index);
  }
  /**
   * <code>repeated .protobuf.ServerBody body = 5;</code>
   */
  @java.lang.Override
  public ltd.finelink.tool.disk.protobuf.ServerBodyOrBuilder getBodyOrBuilder(
      int index) {
    return body_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != ltd.finelink.tool.disk.protobuf.ServerMessage.ServerMsgType.SYSTEM.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(biz_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, biz_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, traceId_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(4, timestamp_);
    }
    for (int i = 0; i < body_.size(); i++) {
      output.writeMessage(5, body_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != ltd.finelink.tool.disk.protobuf.ServerMessage.ServerMsgType.SYSTEM.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(biz_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, biz_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, traceId_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, timestamp_);
    }
    for (int i = 0; i < body_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, body_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ltd.finelink.tool.disk.protobuf.ServerMessage)) {
      return super.equals(obj);
    }
    ltd.finelink.tool.disk.protobuf.ServerMessage other = (ltd.finelink.tool.disk.protobuf.ServerMessage) obj;

    if (type_ != other.type_) return false;
    if (!getBiz()
        .equals(other.getBiz())) return false;
    if (hasTraceId() != other.hasTraceId()) return false;
    if (hasTraceId()) {
      if (!getTraceId()
          .equals(other.getTraceId())) return false;
    }
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!getBodyList()
        .equals(other.getBodyList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + BIZ_FIELD_NUMBER;
    hash = (53 * hash) + getBiz().hashCode();
    if (hasTraceId()) {
      hash = (37 * hash) + TRACEID_FIELD_NUMBER;
      hash = (53 * hash) + getTraceId().hashCode();
    }
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    if (getBodyCount() > 0) {
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBodyList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ltd.finelink.tool.disk.protobuf.ServerMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ltd.finelink.tool.disk.protobuf.ServerMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ltd.finelink.tool.disk.protobuf.ServerMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ltd.finelink.tool.disk.protobuf.ServerMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ltd.finelink.tool.disk.protobuf.ServerMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ltd.finelink.tool.disk.protobuf.ServerMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ltd.finelink.tool.disk.protobuf.ServerMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ltd.finelink.tool.disk.protobuf.ServerMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ltd.finelink.tool.disk.protobuf.ServerMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ltd.finelink.tool.disk.protobuf.ServerMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ltd.finelink.tool.disk.protobuf.ServerMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ltd.finelink.tool.disk.protobuf.ServerMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ltd.finelink.tool.disk.protobuf.ServerMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protobuf.ServerMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protobuf.ServerMessage)
      ltd.finelink.tool.disk.protobuf.ServerMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ltd.finelink.tool.disk.protobuf.ServerProto.internal_static_protobuf_ServerMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ltd.finelink.tool.disk.protobuf.ServerProto.internal_static_protobuf_ServerMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ltd.finelink.tool.disk.protobuf.ServerMessage.class, ltd.finelink.tool.disk.protobuf.ServerMessage.Builder.class);
    }

    // Construct using ltd.finelink.tool.disk.protobuf.ServerMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBodyFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      type_ = 0;

      biz_ = "";

      traceId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      timestamp_ = 0L;

      if (bodyBuilder_ == null) {
        body_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        bodyBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ltd.finelink.tool.disk.protobuf.ServerProto.internal_static_protobuf_ServerMessage_descriptor;
    }

    @java.lang.Override
    public ltd.finelink.tool.disk.protobuf.ServerMessage getDefaultInstanceForType() {
      return ltd.finelink.tool.disk.protobuf.ServerMessage.getDefaultInstance();
    }

    @java.lang.Override
    public ltd.finelink.tool.disk.protobuf.ServerMessage build() {
      ltd.finelink.tool.disk.protobuf.ServerMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ltd.finelink.tool.disk.protobuf.ServerMessage buildPartial() {
      ltd.finelink.tool.disk.protobuf.ServerMessage result = new ltd.finelink.tool.disk.protobuf.ServerMessage(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.type_ = type_;
      result.biz_ = biz_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.traceId_ = traceId_;
      result.timestamp_ = timestamp_;
      if (bodyBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          body_ = java.util.Collections.unmodifiableList(body_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.body_ = body_;
      } else {
        result.body_ = bodyBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ltd.finelink.tool.disk.protobuf.ServerMessage) {
        return mergeFrom((ltd.finelink.tool.disk.protobuf.ServerMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ltd.finelink.tool.disk.protobuf.ServerMessage other) {
      if (other == ltd.finelink.tool.disk.protobuf.ServerMessage.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (!other.getBiz().isEmpty()) {
        biz_ = other.biz_;
        onChanged();
      }
      if (other.hasTraceId()) {
        bitField0_ |= 0x00000001;
        traceId_ = other.traceId_;
        onChanged();
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (bodyBuilder_ == null) {
        if (!other.body_.isEmpty()) {
          if (body_.isEmpty()) {
            body_ = other.body_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureBodyIsMutable();
            body_.addAll(other.body_);
          }
          onChanged();
        }
      } else {
        if (!other.body_.isEmpty()) {
          if (bodyBuilder_.isEmpty()) {
            bodyBuilder_.dispose();
            bodyBuilder_ = null;
            body_ = other.body_;
            bitField0_ = (bitField0_ & ~0x00000002);
            bodyBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBodyFieldBuilder() : null;
          } else {
            bodyBuilder_.addAllMessages(other.body_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ltd.finelink.tool.disk.protobuf.ServerMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ltd.finelink.tool.disk.protobuf.ServerMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int type_ = 0;
    /**
     * <code>.protobuf.ServerMessage.ServerMsgType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.protobuf.ServerMessage.ServerMsgType type = 1;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.protobuf.ServerMessage.ServerMsgType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public ltd.finelink.tool.disk.protobuf.ServerMessage.ServerMsgType getType() {
      @SuppressWarnings("deprecation")
      ltd.finelink.tool.disk.protobuf.ServerMessage.ServerMsgType result = ltd.finelink.tool.disk.protobuf.ServerMessage.ServerMsgType.valueOf(type_);
      return result == null ? ltd.finelink.tool.disk.protobuf.ServerMessage.ServerMsgType.UNRECOGNIZED : result;
    }
    /**
     * <code>.protobuf.ServerMessage.ServerMsgType type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(ltd.finelink.tool.disk.protobuf.ServerMessage.ServerMsgType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.protobuf.ServerMessage.ServerMsgType type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object biz_ = "";
    /**
     * <code>string biz = 2;</code>
     * @return The biz.
     */
    public java.lang.String getBiz() {
      java.lang.Object ref = biz_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        biz_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string biz = 2;</code>
     * @return The bytes for biz.
     */
    public com.google.protobuf.ByteString
        getBizBytes() {
      java.lang.Object ref = biz_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        biz_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string biz = 2;</code>
     * @param value The biz to set.
     * @return This builder for chaining.
     */
    public Builder setBiz(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      biz_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string biz = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBiz() {
      
      biz_ = getDefaultInstance().getBiz();
      onChanged();
      return this;
    }
    /**
     * <code>string biz = 2;</code>
     * @param value The bytes for biz to set.
     * @return This builder for chaining.
     */
    public Builder setBizBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      biz_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object traceId_ = "";
    /**
     * <code>optional string traceId = 3;</code>
     * @return Whether the traceId field is set.
     */
    public boolean hasTraceId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string traceId = 3;</code>
     * @return The traceId.
     */
    public java.lang.String getTraceId() {
      java.lang.Object ref = traceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        traceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string traceId = 3;</code>
     * @return The bytes for traceId.
     */
    public com.google.protobuf.ByteString
        getTraceIdBytes() {
      java.lang.Object ref = traceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        traceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string traceId = 3;</code>
     * @param value The traceId to set.
     * @return This builder for chaining.
     */
    public Builder setTraceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      traceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string traceId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTraceId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      traceId_ = getDefaultInstance().getTraceId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string traceId = 3;</code>
     * @param value The bytes for traceId to set.
     * @return This builder for chaining.
     */
    public Builder setTraceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      traceId_ = value;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 4;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 4;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<ltd.finelink.tool.disk.protobuf.ServerBody> body_ =
      java.util.Collections.emptyList();
    private void ensureBodyIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        body_ = new java.util.ArrayList<ltd.finelink.tool.disk.protobuf.ServerBody>(body_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        ltd.finelink.tool.disk.protobuf.ServerBody, ltd.finelink.tool.disk.protobuf.ServerBody.Builder, ltd.finelink.tool.disk.protobuf.ServerBodyOrBuilder> bodyBuilder_;

    /**
     * <code>repeated .protobuf.ServerBody body = 5;</code>
     */
    public java.util.List<ltd.finelink.tool.disk.protobuf.ServerBody> getBodyList() {
      if (bodyBuilder_ == null) {
        return java.util.Collections.unmodifiableList(body_);
      } else {
        return bodyBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .protobuf.ServerBody body = 5;</code>
     */
    public int getBodyCount() {
      if (bodyBuilder_ == null) {
        return body_.size();
      } else {
        return bodyBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .protobuf.ServerBody body = 5;</code>
     */
    public ltd.finelink.tool.disk.protobuf.ServerBody getBody(int index) {
      if (bodyBuilder_ == null) {
        return body_.get(index);
      } else {
        return bodyBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .protobuf.ServerBody body = 5;</code>
     */
    public Builder setBody(
        int index, ltd.finelink.tool.disk.protobuf.ServerBody value) {
      if (bodyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBodyIsMutable();
        body_.set(index, value);
        onChanged();
      } else {
        bodyBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.ServerBody body = 5;</code>
     */
    public Builder setBody(
        int index, ltd.finelink.tool.disk.protobuf.ServerBody.Builder builderForValue) {
      if (bodyBuilder_ == null) {
        ensureBodyIsMutable();
        body_.set(index, builderForValue.build());
        onChanged();
      } else {
        bodyBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.ServerBody body = 5;</code>
     */
    public Builder addBody(ltd.finelink.tool.disk.protobuf.ServerBody value) {
      if (bodyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBodyIsMutable();
        body_.add(value);
        onChanged();
      } else {
        bodyBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.ServerBody body = 5;</code>
     */
    public Builder addBody(
        int index, ltd.finelink.tool.disk.protobuf.ServerBody value) {
      if (bodyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBodyIsMutable();
        body_.add(index, value);
        onChanged();
      } else {
        bodyBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.ServerBody body = 5;</code>
     */
    public Builder addBody(
        ltd.finelink.tool.disk.protobuf.ServerBody.Builder builderForValue) {
      if (bodyBuilder_ == null) {
        ensureBodyIsMutable();
        body_.add(builderForValue.build());
        onChanged();
      } else {
        bodyBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.ServerBody body = 5;</code>
     */
    public Builder addBody(
        int index, ltd.finelink.tool.disk.protobuf.ServerBody.Builder builderForValue) {
      if (bodyBuilder_ == null) {
        ensureBodyIsMutable();
        body_.add(index, builderForValue.build());
        onChanged();
      } else {
        bodyBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.ServerBody body = 5;</code>
     */
    public Builder addAllBody(
        java.lang.Iterable<? extends ltd.finelink.tool.disk.protobuf.ServerBody> values) {
      if (bodyBuilder_ == null) {
        ensureBodyIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, body_);
        onChanged();
      } else {
        bodyBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.ServerBody body = 5;</code>
     */
    public Builder clearBody() {
      if (bodyBuilder_ == null) {
        body_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        bodyBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.ServerBody body = 5;</code>
     */
    public Builder removeBody(int index) {
      if (bodyBuilder_ == null) {
        ensureBodyIsMutable();
        body_.remove(index);
        onChanged();
      } else {
        bodyBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.ServerBody body = 5;</code>
     */
    public ltd.finelink.tool.disk.protobuf.ServerBody.Builder getBodyBuilder(
        int index) {
      return getBodyFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .protobuf.ServerBody body = 5;</code>
     */
    public ltd.finelink.tool.disk.protobuf.ServerBodyOrBuilder getBodyOrBuilder(
        int index) {
      if (bodyBuilder_ == null) {
        return body_.get(index);  } else {
        return bodyBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .protobuf.ServerBody body = 5;</code>
     */
    public java.util.List<? extends ltd.finelink.tool.disk.protobuf.ServerBodyOrBuilder> 
         getBodyOrBuilderList() {
      if (bodyBuilder_ != null) {
        return bodyBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(body_);
      }
    }
    /**
     * <code>repeated .protobuf.ServerBody body = 5;</code>
     */
    public ltd.finelink.tool.disk.protobuf.ServerBody.Builder addBodyBuilder() {
      return getBodyFieldBuilder().addBuilder(
          ltd.finelink.tool.disk.protobuf.ServerBody.getDefaultInstance());
    }
    /**
     * <code>repeated .protobuf.ServerBody body = 5;</code>
     */
    public ltd.finelink.tool.disk.protobuf.ServerBody.Builder addBodyBuilder(
        int index) {
      return getBodyFieldBuilder().addBuilder(
          index, ltd.finelink.tool.disk.protobuf.ServerBody.getDefaultInstance());
    }
    /**
     * <code>repeated .protobuf.ServerBody body = 5;</code>
     */
    public java.util.List<ltd.finelink.tool.disk.protobuf.ServerBody.Builder> 
         getBodyBuilderList() {
      return getBodyFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        ltd.finelink.tool.disk.protobuf.ServerBody, ltd.finelink.tool.disk.protobuf.ServerBody.Builder, ltd.finelink.tool.disk.protobuf.ServerBodyOrBuilder> 
        getBodyFieldBuilder() {
      if (bodyBuilder_ == null) {
        bodyBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            ltd.finelink.tool.disk.protobuf.ServerBody, ltd.finelink.tool.disk.protobuf.ServerBody.Builder, ltd.finelink.tool.disk.protobuf.ServerBodyOrBuilder>(
                body_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      return bodyBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protobuf.ServerMessage)
  }

  // @@protoc_insertion_point(class_scope:protobuf.ServerMessage)
  private static final ltd.finelink.tool.disk.protobuf.ServerMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ltd.finelink.tool.disk.protobuf.ServerMessage();
  }

  public static ltd.finelink.tool.disk.protobuf.ServerMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ServerMessage>
      PARSER = new com.google.protobuf.AbstractParser<ServerMessage>() {
    @java.lang.Override
    public ServerMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ServerMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ServerMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ServerMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ltd.finelink.tool.disk.protobuf.ServerMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

