// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/proto/server_message.proto

package ltd.finelink.tool.disk.protobuf;

public interface ServerMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.ServerMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.protobuf.ServerMessage.ServerMsgType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.protobuf.ServerMessage.ServerMsgType type = 1;</code>
   * @return The type.
   */
  ltd.finelink.tool.disk.protobuf.ServerMessage.ServerMsgType getType();

  /**
   * <code>string biz = 2;</code>
   * @return The biz.
   */
  java.lang.String getBiz();
  /**
   * <code>string biz = 2;</code>
   * @return The bytes for biz.
   */
  com.google.protobuf.ByteString
      getBizBytes();

  /**
   * <code>optional string traceId = 3;</code>
   * @return Whether the traceId field is set.
   */
  boolean hasTraceId();
  /**
   * <code>optional string traceId = 3;</code>
   * @return The traceId.
   */
  java.lang.String getTraceId();
  /**
   * <code>optional string traceId = 3;</code>
   * @return The bytes for traceId.
   */
  com.google.protobuf.ByteString
      getTraceIdBytes();

  /**
   * <code>int64 timestamp = 4;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>repeated .protobuf.ServerBody body = 5;</code>
   */
  java.util.List<ltd.finelink.tool.disk.protobuf.ServerBody> 
      getBodyList();
  /**
   * <code>repeated .protobuf.ServerBody body = 5;</code>
   */
  ltd.finelink.tool.disk.protobuf.ServerBody getBody(int index);
  /**
   * <code>repeated .protobuf.ServerBody body = 5;</code>
   */
  int getBodyCount();
  /**
   * <code>repeated .protobuf.ServerBody body = 5;</code>
   */
  java.util.List<? extends ltd.finelink.tool.disk.protobuf.ServerBodyOrBuilder> 
      getBodyOrBuilderList();
  /**
   * <code>repeated .protobuf.ServerBody body = 5;</code>
   */
  ltd.finelink.tool.disk.protobuf.ServerBodyOrBuilder getBodyOrBuilder(
      int index);
}
